services:
  - type: web
    name: calculadora-investimentos-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend/app && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0

  - type: web
    name: calculadora-investimentos-frontend
    env: static
    buildCommand: echo "Frontend build complete"
    startCommand: echo "Frontend ready"
    staticPublishPath: ./frontend 